### ISSUE TITLE
Capitalized words in load_dict() are not found

### ISSUE THREAD

**Issue by manestay** [mholtzscher/syllapy#57]
* SyllaPy version: 0.4.0
* Python version: 3.6.6
* Operating System: Ubuntu 16.04

### Description
Words such as 'Ohio' and 'Norway' exist in dict returned from load_dict(). However, when you call syllapy.count('Ohio'), the count() function converts it to lowercase, so it is not found in the dictionary, and 2 is returned instead of the value of 3 in the dict.

**Comment by mholtzscher** [comment]
Thanks for bringing this to my attention. I thought I had lowercased all the words in the dataset but apparently I missed that. I will lowercase the dataset and get a new release out this week

**Comment by mholtzscher** [comment]
I released 0.5.0 which should solve this @manestay

**Comment by manestay** [comment]
Great! Thanks a lot.
