### ISSUE TITLE
Are you still interested in maintaining this project?

### ISSUE THREAD

**Issue by harrisj** [mholtzscher/syllapy#86]
Hello there!

Thank you for writing syllapy! I have used it to help relaunch the NYT Haiku Twitter bot (see [the Github repo](https://github.com/harrisj/nyt-haiku-python) for details) and it was such a tremendous relief to be able to use your library instead of keeping a dictionary of syllable counts I had to load. I would like to contribute some things back to this repo though and I wanted to check if you still were interested in maintaining it so I'm not bothering you incessantly if you don't have the time or bandwidth? Thank you.

**Comment by mholtzscher** [comment]
Hi! I'm glad you are enjoying this library. I am still interested in maintaining it. I haven't had much free time the last few months but my scheduled has lightened a lot lately. I will work on getting your changes validated and merged this week.

**Comment by harrisj** [comment]
Thank you! I just wanted to check before I bothered you too much!
